name: Check for master or prod failure

on:
  workflow_run:
    workflows: [Test integration tests]
    types: [completed]
    branches: [main,prod]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.conclusion == 'timed_out'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
        
      - name: Get all dependancy
        run: go mod tidy
      
      - name: tests
        run: |
          cd cmd  
          go run main.go "https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"