name: Test integration tests

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
        
      - name: Get all dependancy
        run: go mod tidy
      
      - name: tests
        run: go test -v internal/tests/integration/*_test.go

